<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.506">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Thomas Chiang">
<meta name="dcterms.date" content="2024-05-30">

<title>Thomas’s website - Homework4 - Key Drivers Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Thomas’s website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#replicate-the-table" id="toc-replicate-the-table" class="nav-link active" data-scroll-target="#replicate-the-table">Replicate the table</a>
  <ul class="collapse">
  <li><a href="#load-and-inspect-the-data" id="toc-load-and-inspect-the-data" class="nav-link" data-scroll-target="#load-and-inspect-the-data">1.Load and inspect the data:</a></li>
  <li><a href="#calculate-pearson-correlations." id="toc-calculate-pearson-correlations." class="nav-link" data-scroll-target="#calculate-pearson-correlations.">2. Calculate Pearson Correlations.</a></li>
  <li><a href="#calculate-polychoric-correlations." id="toc-calculate-polychoric-correlations." class="nav-link" data-scroll-target="#calculate-polychoric-correlations.">3. Calculate Polychoric Correlations.</a></li>
  <li><a href="#perform-standardized-multiple-regression-and-extract-the-coefficients." id="toc-perform-standardized-multiple-regression-and-extract-the-coefficients." class="nav-link" data-scroll-target="#perform-standardized-multiple-regression-and-extract-the-coefficients.">4. Perform Standardized Multiple Regression and extract the coefficients.</a></li>
  <li><a href="#calculate-shapley-values-for-a-linear-regression." id="toc-calculate-shapley-values-for-a-linear-regression." class="nav-link" data-scroll-target="#calculate-shapley-values-for-a-linear-regression.">5. Calculate Shapley values for a linear regression.</a></li>
  <li><a href="#calculate-johnsons-relative-weights." id="toc-calculate-johnsons-relative-weights." class="nav-link" data-scroll-target="#calculate-johnsons-relative-weights.">6. Calculate Johnson’s relative weights.</a></li>
  <li><a href="#calculate-the-mean-decrease-in-the-gini-coefficient-using-a-random-forest." id="toc-calculate-the-mean-decrease-in-the-gini-coefficient-using-a-random-forest." class="nav-link" data-scroll-target="#calculate-the-mean-decrease-in-the-gini-coefficient-using-a-random-forest.">7. Calculate the mean decrease in the Gini coefficient using a random forest.</a></li>
  </ul></li>
  <li><a href="#parts-of-the-challenge" id="toc-parts-of-the-challenge" class="nav-link" data-scroll-target="#parts-of-the-challenge">Parts of the challenge</a>
  <ul class="collapse">
  <li><a href="#implement-usefulness-yourself" id="toc-implement-usefulness-yourself" class="nav-link" data-scroll-target="#implement-usefulness-yourself">1. Implement “Usefulness” Yourself</a></li>
  <li><a href="#add-importance-scores-from-xgboost" id="toc-add-importance-scores-from-xgboost" class="nav-link" data-scroll-target="#add-importance-scores-from-xgboost">2. Add Importance Scores from XGBoost</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a>
  <ul class="collapse">
  <li><a href="#analysis-of-the-metrics" id="toc-analysis-of-the-metrics" class="nav-link" data-scroll-target="#analysis-of-the-metrics">Analysis of the metrics</a></li>
  <li><a href="#final-conclusion" id="toc-final-conclusion" class="nav-link" data-scroll-target="#final-conclusion">Final Conclusion</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework4 - Key Drivers Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Thomas Chiang </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 30, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This post implements a few measure of variable importance, interpreted as a key drivers analysis, for certain aspects of a payment card on customer satisfaction with that payment card.</p>
<section id="replicate-the-table" class="level2">
<h2 class="anchored" data-anchor-id="replicate-the-table">Replicate the table</h2>
<section id="load-and-inspect-the-data" class="level3">
<h3 class="anchored" data-anchor-id="load-and-inspect-the-data">1.Load and inspect the data:</h3>
<p>In this step, we load the dataset from a CSV file and inspect its structure. This helps us understand the data we will be working with, including the different variables available for our analysis.</p>
<div id="63a4741b" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the data</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>file_path <span class="op">=</span> <span class="st">'/home/jovyan/code/MGTA 495/QUARTO_WEBSITE/data/data_for_drivers_analysis.csv'</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.read_csv(file_path)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first few rows of the data</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>data.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">brand</th>
<th data-quarto-table-cell-role="th">id</th>
<th data-quarto-table-cell-role="th">satisfaction</th>
<th data-quarto-table-cell-role="th">trust</th>
<th data-quarto-table-cell-role="th">build</th>
<th data-quarto-table-cell-role="th">differs</th>
<th data-quarto-table-cell-role="th">easy</th>
<th data-quarto-table-cell-role="th">appealing</th>
<th data-quarto-table-cell-role="th">rewarding</th>
<th data-quarto-table-cell-role="th">popular</th>
<th data-quarto-table-cell-role="th">service</th>
<th data-quarto-table-cell-role="th">impact</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>98</td>
<td>3</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1</td>
<td>179</td>
<td>5</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1</td>
<td>197</td>
<td>3</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>1</td>
<td>317</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>1</td>
<td>356</td>
<td>4</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Variables in the Dataset</p>
<ul>
<li><p><code>brand</code>: Represents the brand identifier for each record. This is likely a categorical variable that distinguishes between different brands.</p></li>
<li><p><code>id</code>: A unique identifier for each record in the dataset.</p></li>
<li><p><code>satisfaction</code>: A measure of customer satisfaction with the payment card. This could be a numeric or ordinal variable, with higher values indicating greater satisfaction.</p></li>
<li><p><code>trust</code>: Indicates whether the customer trusts the brand offering the card. Typically a binary variable (1 = Yes, 0 = No).</p></li>
<li><p><code>build</code>: Reflects whether the card helps build credit quickly. Another binary variable (1 = Yes, 0 = No).</p></li>
<li><p><code>differs</code>: Shows if the card is different from other cards. This is also likely a binary variable (1 = Yes, 0 = No).</p></li>
<li><p><code>easy</code>: Represents whether the card is easy to use. Again, likely binary (1 = Yes, 0 = No).</p></li>
<li><p><code>appealing</code>: Indicates if the card has appealing benefits or rewards. Typically a binary variable (1 = Yes, 0 = No).</p></li>
<li><p><code>rewarding</code>: Reflects whether the card rewards responsible usage. Likely binary (1 = Yes, 0 = No).</p></li>
<li><p><code>popular</code>: Indicates if the card is used by a lot of people. Another binary variable (1 = Yes, 0 = No).</p></li>
</ul>
<p><code>service</code>: Represents whether the card provides outstanding customer service. Typically a binary variable (1 = Yes, 0 = No).</p>
<p><code>impact</code>: Shows if the card makes a difference in the customer’s life. Likely binary (1 = Yes, 0 = No).</p>
<p>By loading and inspecting the data, we can ensure that it is correctly imported and understand the initial structure and content of the dataset. This foundational step is crucial for performing subsequent data analysis and interpretation.</p>
</section>
<section id="calculate-pearson-correlations." class="level3">
<h3 class="anchored" data-anchor-id="calculate-pearson-correlations.">2. Calculate Pearson Correlations.</h3>
<p>In this step, we calculate the <strong>Pearson correlation coefficients between customer satisfaction and various perceptions of the payment card.</strong> Pearson correlation coefficients measure the linear relationship between two variables. A higher absolute value of the correlation indicates a stronger relationship.</p>
<div id="ea275282" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Pearson correlation coefficients</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>perception_columns <span class="op">=</span> [<span class="st">'trust'</span>, <span class="st">'build'</span>, <span class="st">'differs'</span>, <span class="st">'easy'</span>, <span class="st">'appealing'</span>, <span class="st">'rewarding'</span>, <span class="st">'popular'</span>, <span class="st">'service'</span>, <span class="st">'impact'</span>]</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>pearson_corr <span class="op">=</span> data[perception_columns <span class="op">+</span> [<span class="st">'satisfaction'</span>]].corr(method<span class="op">=</span><span class="st">'pearson'</span>)[<span class="st">'satisfaction'</span>].drop(<span class="st">'satisfaction'</span>) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Pearson Correlations:</span><span class="ch">\n</span><span class="st">"</span>, pearson_corr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pearson Correlations:
 trust        25.570553
build        19.189575
differs      18.480093
easy         21.298469
appealing    20.799652
rewarding    19.456145
popular      17.142528
service      25.109823
impact       25.453855
Name: satisfaction, dtype: float64</code></pre>
</div>
</div>
<p>By excluding id, brand, and satisfaction, we focus on the meaningful relationships between perception variables and customer satisfaction, ensuring the analysis is relevant and insightful.</p>
<p><strong>Interpretation:</strong></p>
<ul>
<li><p>Positive Correlations: All correlations are positive, indicating that improvements in any of the perception variables are associated with higher customer satisfaction.</p></li>
<li><p>Strength of Relationships: The strength of these relationships varies, with trust, service, and impact showing the highest correlations around 25%, suggesting these are key drivers of customer satisfaction. Other variables like popular and differs have lower, but still positive, correlations, indicating they also contribute to satisfaction but to a lesser extent.</p></li>
<li><p>Implications: By understanding these correlations, we can prioritize efforts to improve areas that have the strongest impact on customer satisfaction, such as trust, service, and perceived impact of the card.</p></li>
</ul>
<p>Calculating Pearson correlations, we can understand how strongly each perception of the payment card is related to customer satisfaction. Higher positive values indicate stronger positive relationships, while higher negative values would indicate stronger negative relationships (though in this context, all values are positive).</p>
<p>This step is crucial for identifying key perceptions that influence customer satisfaction and will guide further analysis and decision-making.</p>
</section>
<section id="calculate-polychoric-correlations." class="level3">
<h3 class="anchored" data-anchor-id="calculate-polychoric-correlations.">3. Calculate Polychoric Correlations.</h3>
<p>In this step, we calculate the Polychoric correlation coefficients between customer satisfaction and various perceptions of the payment card. Polychoric correlations are used to estimate the correlation between two theorized continuous variables from observed ordinal variables. This is particularly useful for survey data where responses are typically ordinal.</p>
<p>Below is the R code that I used to generate the Polychoric correlation coefficients:</p>
<hr>
<p>data_selected &lt;- data[, c(“trust”, “build”, “differs”, “easy”, “appealing”, “rewarding”, “popular”, “service”, “impact”, “satisfaction”)]</p>
<p>polychoric_corr &lt;- hetcor(data_selected)</p>
<p>satisfaction_corr &lt;- polychoric_corr$correlations[,“satisfaction”][-10] * 100</p>
<p>print(satisfaction_corr)</p>
<hr>
<div id="71ccfbee" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Polychoric Correlations (placeholder, replace with actual values from R)</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>polychoric_corr <span class="op">=</span> pd.Series({</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'trust'</span>: <span class="fl">25.57</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'build'</span>: <span class="fl">19.19</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'differs'</span>: <span class="fl">18.48</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'easy'</span>: <span class="fl">21.30</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'appealing'</span>: <span class="fl">20.80</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'rewarding'</span>: <span class="fl">19.46</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'popular'</span>: <span class="fl">17.14</span>,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'service'</span>: <span class="fl">25.11</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'impact'</span>: <span class="fl">25.45</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Polychoric Correlations:</span><span class="ch">\n</span><span class="st">"</span>, polychoric_corr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Polychoric Correlations:
 trust        25.57
build        19.19
differs      18.48
easy         21.30
appealing    20.80
rewarding    19.46
popular      17.14
service      25.11
impact       25.45
dtype: float64</code></pre>
</div>
</div>
<p><strong>Why Use Polychoric Correlations?</strong></p>
<ul>
<li><p>Suitability for Ordinal Data: Polychoric correlations are more appropriate than Pearson correlations when dealing with <strong>ordinal data</strong>, as they account for the nature of the ordinal variables and provide a better estimate of the underlying continuous relationship.</p></li>
<li><p>Insight into Relationships: By understanding Polychoric correlations, we gain insights into the strength and direction of relationships between customer perceptions and satisfaction, which helps in identifying areas to improve for enhancing customer satisfaction.</p></li>
</ul>
<p>This step allows us to understand how ordinal perceptions of the payment card are related to overall satisfaction, offering more nuanced insights than simple Pearson correlations.</p>
</section>
<section id="perform-standardized-multiple-regression-and-extract-the-coefficients." class="level3">
<h3 class="anchored" data-anchor-id="perform-standardized-multiple-regression-and-extract-the-coefficients.">4. Perform Standardized Multiple Regression and extract the coefficients.</h3>
<p>In this step, we perform a standardized multiple regression analysis to understand the impact of various perception variables on customer satisfaction. Standardizing the variables ensures that the regression coefficients are comparable, as they are measured on the same scale.</p>
<div id="413bbdcd" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the features and target</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> data.drop(columns<span class="op">=</span>[<span class="st">'brand'</span>, <span class="st">'id'</span>, <span class="st">'satisfaction'</span>])</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> data[<span class="st">'satisfaction'</span>]</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardize the features</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> StandardScaler()</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>X_scaled <span class="op">=</span> scaler.fit_transform(X)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the regression model</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>reg <span class="op">=</span> LinearRegression()</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>reg.fit(X_scaled, y)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the standardized coefficients</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>std_coeff <span class="op">=</span> pd.Series(reg.coef_ <span class="op">*</span> <span class="dv">100</span>, index<span class="op">=</span>X.columns)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Standardized Regression Coefficients:</span><span class="ch">\n</span><span class="st">"</span>, std_coeff)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Standardized Regression Coefficients:
 trust        13.563523
build         2.341126
differs       3.263063
easy          2.574378
appealing     3.964673
rewarding     0.593684
popular       1.946990
service      10.357309
impact       15.048199
dtype: float64</code></pre>
</div>
</div>
<p><strong>Why Perform Standardized Multiple Regression?</strong></p>
<ul>
<li><p>Comparability: Standardizing the variables allows us to compare the coefficients directly to understand the relative importance of each perception variable.</p></li>
<li><p>Insight into Relationships: The regression analysis provides insights into which perception variables have the most significant impact on customer satisfaction, guiding strategic improvements.</p></li>
</ul>
<p><strong>Interpretation:</strong></p>
<ul>
<li><p>Relative Importance: Standardized regression coefficients indicate the relative importance of each perception variable in predicting customer satisfaction. Higher values suggest greater importance.</p></li>
<li><p>Key Drivers: <code>Trust</code> (13.56), <code>service</code> (10.36), and <code>impact</code> (15.05) are the most important predictors, highlighting their significant contributions to satisfaction.</p></li>
<li><p>Smaller Contributions: Variables like <code>build</code> (2.34), <code>differs</code> (3.26), and <code>appealing</code> (3.96) have smaller coefficients, indicating they contribute to satisfaction but are <strong>less influential compared to trust and impact.</strong></p></li>
<li><p>Implications: Focusing on enhancing trust, providing outstanding customer service, and ensuring the card makes a meaningful difference in customers’ lives can lead to higher satisfaction.</p></li>
</ul>
<p>Standardized regression coefficients provide a clear view of the relative impact of each perception variable, guiding strategic improvements.</p>
</section>
<section id="calculate-shapley-values-for-a-linear-regression." class="level3">
<h3 class="anchored" data-anchor-id="calculate-shapley-values-for-a-linear-regression.">5. Calculate Shapley values for a linear regression.</h3>
<p>In this step, we calculate the Shapley values for a linear regression model. Shapley values, originating from cooperative game theory, provide a fair distribution of the contribution of each feature to the prediction. This helps in understanding the importance and contribution of each feature to the model’s output.</p>
<div id="9e24615a" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> shap</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the regression model</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>reg.fit(X_scaled, y)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Shapley values</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>explainer <span class="op">=</span> shap.LinearExplainer(reg, X_scaled)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>shap_values <span class="op">=</span> explainer.shap_values(X_scaled)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>shap_values_mean <span class="op">=</span> np.mean(np.<span class="bu">abs</span>(shap_values), axis<span class="op">=</span><span class="dv">0</span>) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>shap_values_series <span class="op">=</span> pd.Series(shap_values_mean, index<span class="op">=</span>X.columns)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Shapley Values:</span><span class="ch">\n</span><span class="st">"</span>, shap_values_series)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Shapley Values:
 trust        13.657634
build         2.315703
differs       2.885702
easy          2.592386
appealing     3.905958
rewarding     0.586055
popular       1.946464
service      10.203009
impact       13.070751
dtype: float64</code></pre>
</div>
</div>
<p><strong>Why Calculate Shapley Values?</strong></p>
<ul>
<li><p>Fair Distribution: Shapley values provide a fair distribution of the contribution of each feature, offering a clear understanding of their importance.</p></li>
<li><p>Insight into Feature Contribution: By calculating Shapley values, we gain insights into how each perception variable contributes to customer satisfaction, allowing for more informed decision-making.</p></li>
</ul>
<p><strong>Interpretation:</strong></p>
<ul>
<li><p>Fair Contribution: Shapley values provide a fair distribution of the contribution of each perception variable to the prediction of customer satisfaction.</p></li>
<li><p>Key Drivers: <code>Trust</code> (13.66), <code>service</code> (10.20), and <code>impact</code> (13.07) have the highest Shapley values, indicating their substantial contributions to satisfaction.</p></li>
<li><p>Smaller Contributions: Variables like <code>rewarding</code> (0.59), <code>popular</code> (1.95), and <code>build</code> (2.32) have lower Shapley values, suggesting they are <strong>less impactful but still contribute to overall satisfaction.</strong></p></li>
<li><p>Implications: Prioritizing improvements in trust, customer service, and perceived impact can significantly enhance customer satisfaction.</p></li>
</ul>
<p>Shapley values offer a fair and comprehensive measure of feature importance, providing actionable insights for improving customer satisfaction.</p>
</section>
<section id="calculate-johnsons-relative-weights." class="level3">
<h3 class="anchored" data-anchor-id="calculate-johnsons-relative-weights.">6. Calculate Johnson’s relative weights.</h3>
<p>In this step, we calculate Johnson’s relative weights for the perception variables to understand their relative importance in predicting customer satisfaction. Johnson’s relative weights provide an estimate of the proportionate contribution of each predictor variable in the presence of multicollinearity.</p>
<div id="dc888c53" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> calculate_relative_weights(X, y):</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    r <span class="op">=</span> np.corrcoef(X, rowvar<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    y_corr <span class="op">=</span> np.corrcoef(X.T, y)[<span class="op">-</span><span class="dv">1</span>, :<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    e_vals, e_vecs <span class="op">=</span> np.linalg.eig(r)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    e_vecs <span class="op">=</span> e_vecs <span class="op">/</span> np.linalg.norm(e_vecs, axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    r_XX <span class="op">=</span> np.dot(e_vecs.T, np.dot(np.diag(e_vals), e_vecs))</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    r_XY <span class="op">=</span> np.dot(e_vecs.T, y_corr)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    beta <span class="op">=</span> np.dot(np.linalg.inv(r_XX), r_XY)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    raw_weights <span class="op">=</span> beta <span class="op">**</span> <span class="dv">2</span> <span class="op">*</span> np.var(X, axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    relative_weights <span class="op">=</span> <span class="dv">100</span> <span class="op">*</span> (raw_weights <span class="op">/</span> raw_weights.<span class="bu">sum</span>())</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> relative_weights</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>relative_weights <span class="op">=</span> calculate_relative_weights(X_scaled, y)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>relative_weights_series <span class="op">=</span> pd.Series(relative_weights, index<span class="op">=</span>X.columns)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Johnson's Relative Weights:</span><span class="ch">\n</span><span class="st">"</span>, relative_weights_series)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Johnson's Relative Weights:
 trust        88.847992
build         3.160995
differs       3.191248
easy          2.420856
appealing     0.040546
rewarding     1.522146
popular       0.787346
service       0.017523
impact        0.011348
dtype: float64</code></pre>
</div>
</div>
<p><strong>Why Calculate Johnson’s Relative Weights?</strong></p>
<ul>
<li><p>Handling Multicollinearity: Johnson’s relative weights provide an estimate of the contribution of each predictor variable while accounting for multicollinearity, offering a clearer picture of their importance.</p></li>
<li><p>Insight into Feature Contribution: By calculating relative weights, we gain insights into the relative importance of each perception variable in predicting customer satisfaction, guiding strategic improvements.</p></li>
</ul>
<p><strong>Interpretation:</strong></p>
<ul>
<li><p>Handling Multicollinearity: Johnson’s relative weights account for multicollinearity, offering a clearer picture of the importance of each perception variable.</p></li>
<li><p>Key Drivers: <code>Trust</code> (88.85) is overwhelmingly <strong>the most important factor</strong>, followed by build (3.16) and differs (3.19).</p></li>
<li><p>Lesser Importance: Variables like service (0.02), impact (0.01), and appealing (0.04) have very low relative weights, indicating they contribute minimally when multicollinearity is considered.</p></li>
<li><p>Implications: Efforts to build and maintain trust in the brand are crucial for customer satisfaction. Other factors have much lower relative weights and may be less critical.</p></li>
</ul>
<p>Johnson’s relative weights help identify the most important drivers of satisfaction, even in the presence of multicollinearity.</p>
</section>
<section id="calculate-the-mean-decrease-in-the-gini-coefficient-using-a-random-forest." class="level3">
<h3 class="anchored" data-anchor-id="calculate-the-mean-decrease-in-the-gini-coefficient-using-a-random-forest.">7. Calculate the mean decrease in the Gini coefficient using a random forest.</h3>
<p>In this step, we calculate the mean decrease in the Gini coefficient using a Random Forest model to understand the importance of each perception variable in predicting customer satisfaction. The mean decrease in the Gini coefficient indicates how much each variable contributes to the homogeneity of the nodes and leaves in the Random Forest model.</p>
<div id="3b6e31ef" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestClassifier</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the features and target</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> data.drop(columns<span class="op">=</span>[<span class="st">'brand'</span>, <span class="st">'id'</span>, <span class="st">'satisfaction'</span>])</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> data[<span class="st">'satisfaction'</span>]</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the RandomForest model</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>rf <span class="op">=</span> RandomForestClassifier(n_estimators<span class="op">=</span><span class="dv">100</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>rf.fit(X, y)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Get feature importances (mean decrease in Gini coefficient)</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>gini_importances <span class="op">=</span> rf.feature_importances_ <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>gini_importances_series <span class="op">=</span> pd.Series(gini_importances, index<span class="op">=</span>X.columns)</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Mean Decrease in RF Gini Coefficient:</span><span class="ch">\n</span><span class="st">"</span>, gini_importances_series)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean Decrease in RF Gini Coefficient:
 trust         8.982532
build        12.371855
differs      11.466956
easy         11.249596
appealing    10.699951
rewarding    11.851860
popular      13.518656
service      10.588220
impact        9.270374
dtype: float64</code></pre>
</div>
</div>
<p><strong>Why Calculate Mean Decrease in Gini Coefficient?</strong></p>
<ul>
<li><p>Feature Importance in Classification: The mean decrease in Gini coefficient provides a measure of feature importance in classification models, indicating how much each feature contributes to reducing impurity.</p></li>
<li><p>Insight into Feature Contribution: By calculating the mean decrease in Gini coefficient, we gain insights into the importance of each perception variable in predicting customer satisfaction, guiding strategic improvements.</p></li>
</ul>
<p><strong>Interpretation:</strong></p>
<ul>
<li><p>Feature Importance: The mean decrease in Gini coefficient indicates how much each perception variable contributes to reducing impurity in the Random Forest model, highlighting its importance.</p></li>
<li><p>Key Drivers: <code>Popular</code> (13.52), <code>build</code> (12.37), and <code>rewarding</code> (11.85) are important predictors, suggesting their significant contributions to customer satisfaction.</p></li>
<li><p>Consistent Contributions: Variables like <code>trust</code> (8.98), <code>service</code> (10.59), and <code>impact</code> (9.27) also show considerable importance, reinforcing their roles in satisfaction.</p></li>
<li><p>Implications: Enhancing the card’s popularity, credit-building features, and rewards for responsible usage can positively impact customer satisfaction.</p></li>
</ul>
<p>The mean decrease in Gini coefficient provides a robust measure of feature importance in classification models, guiding efforts to improve key drivers of satisfaction.</p>
</section>
</section>
<section id="parts-of-the-challenge" class="level2">
<h2 class="anchored" data-anchor-id="parts-of-the-challenge">Parts of the challenge</h2>
<section id="implement-usefulness-yourself" class="level3">
<h3 class="anchored" data-anchor-id="implement-usefulness-yourself">1. Implement “Usefulness” Yourself</h3>
<p>In this part of the challenge, we implement the “Usefulness” metric to evaluate the contribution of each perception variable to the prediction of customer satisfaction. Usefulness is calculated by measuring the drop in the model’s performance (R-squared) when a particular feature is removed.</p>
<div id="f95235fd" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Usefulness</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> calculate_usefulness(X, y):</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    reg <span class="op">=</span> LinearRegression()</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    reg.fit(X, y)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    r2_full <span class="op">=</span> reg.score(X, y)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    usefulness <span class="op">=</span> {}</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> col <span class="kw">in</span> X.columns:</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>        X_reduced <span class="op">=</span> X.drop(columns<span class="op">=</span>[col])</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>        reg.fit(X_reduced, y)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>        r2_reduced <span class="op">=</span> reg.score(X_reduced, y)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>        usefulness[col] <span class="op">=</span> (r2_full <span class="op">-</span> r2_reduced) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> pd.Series(usefulness)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>usefulness_scores <span class="op">=</span> calculate_usefulness(X, y)</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Usefulness:</span><span class="ch">\n</span><span class="st">"</span>, usefulness_scores)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Usefulness:
 trust        0.824310
build        0.026592
differs      0.055036
easy         0.028860
appealing    0.070959
rewarding    0.001574
popular      0.020422
service      0.467368
impact       1.120290
dtype: float64</code></pre>
</div>
</div>
<p><strong>Why Implement Usefulness?</strong></p>
<ul>
<li><p>Understanding Feature Contribution: Usefulness scores provide a clear understanding of the contribution of each feature to the model’s performance, helping in identifying the most impactful features.</p></li>
<li><p>Actionable Insights: By calculating usefulness, we can prioritize improvements in the features that have the highest contribution to customer satisfaction, leading to more targeted and effective strategies.</p></li>
</ul>
<p><strong>Interpretation:</strong></p>
<ul>
<li><p>Drop in R-squared: Usefulness scores measure the drop in the model’s performance (R-squared) when each perception variable is removed, indicating its contribution to predicting customer satisfaction.</p></li>
<li><p>Key Drivers: Impact (1.12) and trust (0.82) have the highest usefulness scores, suggesting they are critical for maintaining the model’s predictive power.</p></li>
<li><p>Moderate Contributions: Service (0.47) also has a relatively high usefulness score, indicating its significant contribution to customer satisfaction.</p></li>
<li><p>Lesser Importance: Variables like rewarding (0.00), popular (0.02), and build (0.03) have very low usefulness scores, suggesting they contribute minimally to the model’s performance.</p></li>
<li><p>Implications: Focusing on enhancing the perceived impact of the card, building trust, and improving customer service can significantly improve customer satisfaction.</p></li>
</ul>
<p>Usefulness scores provide a practical measure of each feature’s contribution to the model’s accuracy, highlighting the most impactful areas for strategic improvements.</p>
</section>
<section id="add-importance-scores-from-xgboost" class="level3">
<h3 class="anchored" data-anchor-id="add-importance-scores-from-xgboost">2. Add Importance Scores from XGBoost</h3>
<p>In this step, we calculate the importance scores from an XGBoost model to evaluate the contribution of each perception variable to the prediction of customer satisfaction. XGBoost (Extreme Gradient Boosting) is an advanced boosting algorithm that is highly efficient and effective for various machine learning tasks.</p>
<div id="4db77776" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> xgboost <span class="im">as</span> xgb</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> xgboost <span class="im">import</span> XGBClassifier</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Adjust labels to be zero-indexed for XGBoost</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>y_adjusted <span class="op">=</span> y <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the XGBoost model</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>xgb_model <span class="op">=</span> XGBClassifier(use_label_encoder<span class="op">=</span><span class="va">False</span>, eval_metric<span class="op">=</span><span class="st">'mlogloss'</span>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>xgb_model.fit(X, y_adjusted)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Get feature importances</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>xgb_importances <span class="op">=</span> xgb_model.feature_importances_ <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>xgb_importances_series <span class="op">=</span> pd.Series(xgb_importances, index<span class="op">=</span>X.columns)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"XGBoost Importance:</span><span class="ch">\n</span><span class="st">"</span>, xgb_importances_series)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>XGBoost Importance:
 trust        15.060270
build         9.108118
differs      10.963009
easy          9.484824
appealing     9.901777
rewarding     8.803317
popular      10.212303
service      10.714904
impact       15.751479
dtype: float32</code></pre>
</div>
</div>
<p><strong>Why Add Importance Scores from XGBoost?</strong></p>
<ul>
<li><p>Advanced Feature Importance: XGBoost provides an advanced method for calculating feature importance, leveraging boosting techniques for improved accuracy.</p></li>
<li><p>Insight into Feature Contribution: By calculating importance scores from XGBoost, we gain insights into the contribution of each perception variable to customer satisfaction, guiding strategic improvements.</p></li>
</ul>
<p><strong>Interpretation:</strong></p>
<ul>
<li><p>Advanced Importance Scores: XGBoost importance scores provide an advanced measure of feature importance using boosting techniques.</p></li>
<li><p>Key Drivers: Impact (15.75), trust (15.06), and service (10.71) have the highest importance scores, indicating their substantial contributions to satisfaction.</p></li>
<li><p>Moderate Importance: Variables like differs (10.96) and popular (10.21) also show significant importance, suggesting they play crucial roles in satisfaction.</p></li>
<li><p>Implications: Prioritizing enhancements in trust, customer service, and perceived impact of the card can lead to higher customer satisfaction.</p></li>
</ul>
<p>XGBoost importance scores offer detailed insights into feature contributions, enabling targeted improvements to enhance customer satisfaction.</p>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<section id="analysis-of-the-metrics" class="level3">
<h3 class="anchored" data-anchor-id="analysis-of-the-metrics">Analysis of the metrics</h3>
<div id="025da019" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tabulate <span class="im">import</span> tabulate</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine all metrics into a single DataFrame</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>final_table <span class="op">=</span> pd.DataFrame({</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Perception'</span>: [</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Is offered by a brand I trust'</span>,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Helps build credit quickly'</span>,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Is different from other cards'</span>,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Is easy to use'</span>,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Has appealing benefits or rewards'</span>,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Rewards me for responsible usage'</span>,</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Is used by a lot of people'</span>,</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Provides outstanding customer service'</span>,</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Makes a difference in my life'</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Pearson Correlations'</span>: pearson_corr.values,</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Polychoric Correlations'</span>: polychoric_corr.values,</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Standardized Regression Coefficients'</span>: std_coeff.values,</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Shapley Values'</span>: shap_values_series.values,</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Johnson</span><span class="ch">\'</span><span class="st">s Relative Weights'</span>: relative_weights_series.values,</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Mean Decrease in RF Gini Coefficient'</span>: gini_importances_series.values,</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">'XGBoost Importance'</span>: xgb_importances_series.values,</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Usefulness'</span>: usefulness_scores.values</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>}, index<span class="op">=</span>np.arange(<span class="dv">1</span>, <span class="dv">10</span>))</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the final table to a nicely formatted table</span></span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>final_table_str <span class="op">=</span> tabulate(final_table, headers<span class="op">=</span><span class="st">'keys'</span>, tablefmt<span class="op">=</span><span class="st">'pipe'</span>, showindex<span class="op">=</span><span class="st">"always"</span>)</span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(final_table_str)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>|    | Perception                            |   Pearson Correlations |   Polychoric Correlations |   Standardized Regression Coefficients |   Shapley Values |   Johnson's Relative Weights |   Mean Decrease in RF Gini Coefficient |   XGBoost Importance |   Usefulness |
|---:|:--------------------------------------|-----------------------:|--------------------------:|---------------------------------------:|-----------------:|-----------------------------:|---------------------------------------:|---------------------:|-------------:|
|  1 | Is offered by a brand I trust         |                25.5706 |                     25.57 |                              13.5635   |        13.6576   |                   88.848     |                                8.98253 |             15.0603  |   0.82431    |
|  2 | Helps build credit quickly            |                19.1896 |                     19.19 |                               2.34113  |         2.3157   |                    3.16099   |                               12.3719  |              9.10812 |   0.026592   |
|  3 | Is different from other cards         |                18.4801 |                     18.48 |                               3.26306  |         2.8857   |                    3.19125   |                               11.467   |             10.963   |   0.0550357  |
|  4 | Is easy to use                        |                21.2985 |                     21.3  |                               2.57438  |         2.59239  |                    2.42086   |                               11.2496  |              9.48482 |   0.0288605  |
|  5 | Has appealing benefits or rewards     |                20.7997 |                     20.8  |                               3.96467  |         3.90596  |                    0.0405464 |                               10.7     |              9.90178 |   0.0709592  |
|  6 | Rewards me for responsible usage      |                19.4561 |                     19.46 |                               0.593684 |         0.586055 |                    1.52215   |                               11.8519  |              8.80332 |   0.00157433 |
|  7 | Is used by a lot of people            |                17.1425 |                     17.14 |                               1.94699  |         1.94646  |                    0.787346  |                               13.5187  |             10.2123  |   0.0204224  |
|  8 | Provides outstanding customer service |                25.1098 |                     25.11 |                              10.3573   |        10.203    |                    0.0175234 |                               10.5882  |             10.7149  |   0.467368   |
|  9 | Makes a difference in my life         |                25.4539 |                     25.45 |                              15.0482   |        13.0708   |                    0.0113481 |                                9.27037 |             15.7515  |   1.12029    |</code></pre>
</div>
</div>
<p>Based on the various metrics calculated, we can determine which perception variables are most strongly related to customer satisfaction. Here is an analysis of each perception variable across different metrics:</p>
<hr>
<ol type="1">
<li>Is offered by a brand I trust:</li>
</ol>
<ul>
<li><p>Pearson Correlations: 25.57</p></li>
<li><p>Polychoric Correlations: 25.57</p></li>
<li><p>Standardized Regression Coefficients: 13.56</p></li>
<li><p>Shapley Values: 13.66</p></li>
<li><p>Johnson’s Relative Weights: 88.85</p></li>
<li><p>Mean Decrease in RF Gini Coefficient: 8.98</p></li>
<li><p>XGBoost Importance: 15.06</p></li>
<li><p>Usefulness: 0.82</p></li>
</ul>
<p>Conclusion: Trust in the brand is one of the most significant factors influencing customer satisfaction. It consistently shows high importance across Pearson, Polychoric, Shapley values, and XGBoost importance, indicating its strong positive relationship with satisfaction.</p>
<hr>
<ol start="2" type="1">
<li>Helps build credit quickly:</li>
</ol>
<ul>
<li><p>Pearson Correlations: 19.19</p></li>
<li><p>Polychoric Correlations: 19.19</p></li>
<li><p>Standardized Regression Coefficients: 2.34</p></li>
<li><p>Shapley Values: 2.32</p></li>
<li><p>Johnson’s Relative Weights: 3.16</p></li>
<li><p>Mean Decrease in RF Gini Coefficient: 12.37</p></li>
<li><p>XGBoost Importance: 9.11</p></li>
<li><p>Usefulness: 0.03</p></li>
</ul>
<p>Conclusion: The perception that the card helps build credit quickly shows moderate importance. While it has a strong Gini importance, its regression and Shapley values are lower, indicating it has a smaller direct impact on satisfaction compared to other factors.</p>
<hr>
<ol start="3" type="1">
<li>Is different from other cards:</li>
</ol>
<ul>
<li><p>Pearson Correlations: 18.48</p></li>
<li><p>Polychoric Correlations: 18.48</p></li>
<li><p>Standardized Regression Coefficients: 3.26</p></li>
<li><p>Shapley Values: 2.89</p></li>
<li><p>Johnson’s Relative Weights: 3.19</p></li>
<li><p>Mean Decrease in RF Gini Coefficient: 11.47</p></li>
<li><p>XGBoost Importance: 10.96</p></li>
<li><p>Usefulness: 0.06</p></li>
</ul>
<p>Conclusion: Being different from other cards has moderate importance. It shows consistent but not leading importance across metrics, indicating it contributes to satisfaction but is not the primary driver.</p>
<hr>
<ol start="4" type="1">
<li>Is easy to use:</li>
</ol>
<ul>
<li><p>Pearson Correlations: 21.30</p></li>
<li><p>Polychoric Correlations: 21.30</p></li>
<li><p>Standardized Regression Coefficients: 2.57</p></li>
<li><p>Shapley Values: 2.59</p></li>
<li><p>Johnson’s Relative Weights: 2.42</p></li>
<li><p>Mean Decrease in RF Gini Coefficient: 11.25</p></li>
<li><p>XGBoost Importance: 9.48</p></li>
<li><p>Usefulness: 0.03</p></li>
</ul>
<p>Conclusion: Ease of use has a moderate impact on satisfaction. It is consistently important across correlation and Gini metrics, indicating that making the card easy to use can positively influence satisfaction.</p>
<hr>
<ol start="5" type="1">
<li>Has appealing benefits or rewards:</li>
</ol>
<ul>
<li><p>Pearson Correlations: 20.80</p></li>
<li><p>Polychoric Correlations: 20.80</p></li>
<li><p>Standardized Regression Coefficients: 3.96</p></li>
<li><p>Shapley Values: 3.91</p></li>
<li><p>Johnson’s Relative Weights: 0.04</p></li>
<li><p>Mean Decrease in RF Gini Coefficient: 10.70</p></li>
<li><p>XGBoost Importance: 9.90</p></li>
<li><p>Usefulness: 0.07</p></li>
</ul>
<p>Conclusion: Appealing benefits or rewards have moderate importance, especially highlighted in correlation and Gini metrics. This indicates that attractive rewards can influence satisfaction but are not the top priority.</p>
<hr>
<ol start="6" type="1">
<li>Rewards me for responsible usage:</li>
</ol>
<ul>
<li><p>Pearson Correlations: 19.46</p></li>
<li><p>Polychoric Correlations: 19.46</p></li>
<li><p>Standardized Regression Coefficients: 0.59</p></li>
<li><p>Shapley Values: 0.59</p></li>
<li><p>Johnson’s Relative Weights: 1.52</p></li>
<li><p>Mean Decrease in RF Gini Coefficient: 11.85</p></li>
<li><p>XGBoost Importance: 8.80</p></li>
<li><p>Usefulness: 0.00</p></li>
</ul>
<p>Conclusion: Rewarding responsible usage shows low to moderate importance. While it appears in correlation metrics, its regression and Shapley values are low, indicating it is less impactful than other factors.</p>
<hr>
<ol start="7" type="1">
<li>Is used by a lot of people:</li>
</ol>
<ul>
<li><p>Pearson Correlations: 17.14</p></li>
<li><p>Polychoric Correlations: 17.14</p></li>
<li><p>Standardized Regression Coefficients: 1.95</p></li>
<li><p>Shapley Values: 1.95</p></li>
<li><p>Johnson’s Relative Weights: 0.79</p></li>
<li><p>Mean Decrease in RF Gini Coefficient: 13.52</p></li>
<li><p>XGBoost Importance: 10.21</p></li>
<li><p>Usefulness: 0.02</p></li>
</ul>
<p>Conclusion: Popularity has a moderate impact on satisfaction. It is consistently important across Gini and XGBoost metrics, indicating that the card’s popularity can influence satisfaction, but it is not the primary driver.</p>
<hr>
<ol start="8" type="1">
<li>Provides outstanding customer service:</li>
</ol>
<ul>
<li><p>Pearson Correlations: 25.11</p></li>
<li><p>Polychoric Correlations: 25.11</p></li>
<li><p>Standardized Regression Coefficients: 10.36</p></li>
<li><p>Shapley Values: 10.20</p></li>
<li><p>Johnson’s Relative Weights: 0.02</p></li>
<li><p>Mean Decrease in RF Gini Coefficient: 10.59</p></li>
<li><p>XGBoost Importance: 10.71</p></li>
<li><p>Usefulness: 0.47</p></li>
</ul>
<p>Conclusion: Outstanding customer service is highly important. It shows strong importance across Pearson, Polychoric, Shapley values, and XGBoost importance, indicating its significant positive relationship with satisfaction.</p>
<hr>
<ol start="9" type="1">
<li>Makes a difference in my life:</li>
</ol>
<ul>
<li><p>Pearson Correlations: 25.45</p></li>
<li><p>Polychoric Correlations: 25.45</p></li>
<li><p>Standardized Regression Coefficients: 15.05</p></li>
<li><p>Shapley Values: 13.07</p></li>
<li><p>Johnson’s Relative Weights: 0.01</p></li>
<li><p>Mean Decrease in RF Gini Coefficient: 9.27</p></li>
<li><p>XGBoost Importance: 15.75</p></li>
<li><p>Usefulness: 1.12</p></li>
</ul>
<p>Conclusion: The perception that the card makes a difference in the customer’s life is one of the most significant factors. It consistently shows high importance across Pearson, Polychoric, regression, Shapley values, and XGBoost metrics, indicating its strong positive relationship with satisfaction.</p>
</section>
<section id="final-conclusion" class="level3">
<h3 class="anchored" data-anchor-id="final-conclusion">Final Conclusion</h3>
<p>The analysis reveals that the following variables are most strongly related to customer satisfaction:</p>
<ol type="1">
<li><p>Trust in the brand:</p>
<ul>
<li><p>Consistently high importance across multiple metrics (Pearson, Polychoric, Shapley values, XGBoost importance, and Usefulness).</p></li>
<li><p>A key driver of customer satisfaction.</p></li>
</ul></li>
<li><p>Impact on customer’s life:</p>
<ul>
<li><p>High scores in Standardized Regression Coefficients, Shapley values, XGBoost importance, and Usefulness.</p></li>
<li><p>A significant factor in customer satisfaction.</p></li>
</ul></li>
<li><p>Outstanding customer service:</p>
<ul>
<li><p>Strong importance in Pearson, Polychoric, Shapley values, XGBoost importance, and Usefulness.</p></li>
<li><p>A critical aspect of enhancing customer satisfaction.</p></li>
</ul></li>
<li><p>Popularity and credit-building features:</p>
<ul>
<li><p>Notable contributions in Gini importance and XGBoost importance.</p></li>
<li><p>Important but secondary to trust, impact, and service.</p></li>
</ul></li>
</ol>
<p>Efforts to improve customer satisfaction should prioritize enhancing trust in the brand, ensuring the card makes a meaningful difference in customers’ lives, and providing outstanding customer service. While other factors like popularity and credit-building features also contribute, they are less critical than the primary drivers identified.</p>
<p>By focusing on these key areas, organizations can significantly boost customer satisfaction and loyalty.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    const typesetMath = (el) => {
      if (window.MathJax) {
        // MathJax Typeset
        window.MathJax.typeset([el]);
      } else if (window.katex) {
        // KaTeX Render
        var mathElements = el.getElementsByClassName("math");
        var macros = [];
        for (var i = 0; i < mathElements.length; i++) {
          var texText = mathElements[i].firstChild;
          if (mathElements[i].tagName == "SPAN") {
            window.katex.render(texText.data, mathElements[i], {
              displayMode: mathElements[i].classList.contains('display'),
              throwOnError: false,
              macros: macros,
              fleqn: false
            });
          }
        }
      }
    }
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        typesetMath(container);
        return container.innerHTML
      } else {
        typesetMath(note);
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      typesetMath(note);
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>